### ISSUE TITLE
backlog: Refactor codes and get QuickPick options from metadata

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-spring-initializr#170]
TODO items:

- [x] Address linting errors in code base #171
- [x] Combine interfaces in `./src/hander` #172
- [x] Generate QuickPick Items from fetched metadata #173
