### ISSUE TITLE
0.2.0 Endgame

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode-spring-initializr#47]
## Dev
- [x] Allow user to select Spring Boot version #24 
- [x] Allow to specify default group/artifact Id #28 
- [x] Allow configuration of service endpoint #29 
- [x] Add `User-Agent` header for requests #25 
- [x]  Improve dependencies filtering #26 ( `keywords` not supported, now filter `name` and `description` )
- [x] Update Extension Icon @Matthew-Dong #48 

## Test
- [x] 2/8 Follow [Test Plan](https://github.com/Microsoft/vscode-spring-initializr/wiki/Test-Plan)

## Release
- [x] 2/9 Update Readme & changelog #48 
- [x] 2/9 Merge to master
- [x] 2/9 Trigger release job
- [x] 2/9 Add tag

**Comment by bsaby** [comment]
# 2/8 Run Test Plan
Test case | Windows | OSX | Linux
-- | -- | -- | --
Clean   install | Pass | pass | pass
Update | Pass | pass | pass
Uninstall | Pass | pass | pass
Generate   a Maven Project: Quickstart   with dependency search | Pass | pass | pass
Generate   a Maven Project:Quickstart with last settings | Pass | pass | pass
Generate a Gradle Project: Quickstart with dependency search | Pass | pass | pass
Generate   a Gradle Project: Quickstart   with last settings | Pass | pass | pass
Customized   Spring Initializr Service URL | Pass | pass | Pass
Set default value of   GroupId and ArtifactId | Pass | pass | pass

**Comment by Eskibear** [comment]
icon updated in https://github.com/Microsoft/vscode-spring-initializr/pull/48

**Comment by Eskibear** [comment]
released https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-spring-initializr
